# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: abb0dc9f980186fb0aa63d01772ba4212d4c4add5f1ed2c403ca3f541f1b5c10339c43d867f3246f337a4b90de9517034f65c5649ff1f169bc8cc8b0d93dc87b

test:
  secret_key_base: d6b949c1d14e82cf761d8ac143a724677975d92ee55b00e578fbf9ed53734c3ba9d4884b3672dc904b91b428d00656a50dc844bc872323dbd50e26ad3db3bdf6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
